# Instruction for Dockerfile to create a new image on top of the base image (ubuntu)
# user container

FROM debian

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd -p
RUN echo 'root:mypassword' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
# RUN echo 'PS1="${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"' >> .bashrc
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

# get container ip
#sudo docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' CONTAINER_ID